services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - QUARKUS_PROFILE=dev`
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment: POSTGRES_DB=workspace
      POSTGRES_USER=workspace_user
      POSTGRES_PASSWORD=workspace_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
