// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API support",
            "email": "support@flusso.dev"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/flows": {
            "post": {
                "description": "Create a new flow with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flows"
                ],
                "summary": "Create a new flow",
                "parameters": [
                    {
                        "description": "Flow data",
                        "name": "flow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Flow"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Flow"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to create flow",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flows/": {
            "get": {
                "description": "Retrieve all flows from the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flows"
                ],
                "summary": "Get all flows",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Flow"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve flows",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/flows/{id}": {
            "get": {
                "description": "Retrieve a single flow by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "flows"
                ],
                "summary": "Get a flow by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Flow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Flow"
                        }
                    },
                    "400": {
                        "description": "Invalid flow ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Flow not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Flow": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Timestamp when the flow was created",
                    "type": "string"
                },
                "eventsJSON": {
                    "description": "location of the event",
                    "type": "string"
                },
                "id": {
                    "description": "Primary Key",
                    "type": "integer"
                },
                "name": {
                    "description": "Name of the flow",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Timestamp the flow was last updated",
                    "type": "string"
                },
                "videoURL": {
                    "description": "location of video + audio of recorded event",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Flusso API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
